import {
  Wind,
  Cable,
  Fan,
  Building2,
  Home,
  Refrigerator,
  Trees,
  Zap,
  Flame,
  Shield,
  AlertTriangle,
  Maximize,
  Car,
  ShieldCheck,
} from "lucide-react";

export const amenities = [
  { id: "air-conditioning", label: "Air conditioning", icon: Wind },
  { id: "cable-ready", label: "Cable ready", icon: Cable },
  { id: "ceiling-fan", label: "Ceiling fan", icon: Fan },
  { id: "high-ceilings", label: "High ceilings", icon: Building2 },
  { id: "private-balcony", label: "Private balcony", icon: Home },
  { id: "refrigerator", label: "Refrigerator", icon: Refrigerator },
  { id: "wooded-views", label: "Wooded views", icon: Trees },
  { id: "wd-hookup", label: "W/D hookup", icon: Zap },
  { id: "hardwood-floor-1", label: "Hardwood Floor (home)", icon: Home },
  { id: "hardwood-floor-2", label: "Hardwood Floor (home)", icon: Home },
  { id: "fireplace", label: "Fireplace (home)", icon: Flame },
  { id: "first-aid-kit", label: "First aid kit", icon: Shield },
  {
    id: "carbon-monoxide",
    label: "Carbon monoxide alarm",
    icon: AlertTriangle,
  },
  { id: "expanded-patios", label: "Expanded patios (home)", icon: Maximize },
  { id: "free-parking", label: "Free parking on premises", icon: Car },
  { id: "fire-extinguisher", label: "Fire extinguisher", icon: ShieldCheck },
];
